Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 139, in runscrape
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 124, in launchsite
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
  File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
OSError: [Errno 24] Too many open files
Exception in thread Thread-160:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 513, in _handle_workers
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 337, in _maintain_pool
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/usr/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
OSError: [Errno 24] Too many open files


multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 52, in scrape
    session.close()
  File "/home/william/.local/lib/python3.8/site-packages/requests_html.py", line 736, in close
    self.loop.run_until_complete(self._browser.close())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/browser.py", line 262, in close
    await self._closeCallback()  # Launcher.killChrome()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 218, in killChrome
    self._cleanup_tmp_user_data_dir()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 133, in _cleanup_tmp_user_data_dir
    raise IOError('Unable to remove Temporary User Data')
OSError: Unable to remove Temporary User Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 94, in scrape
    session.close()
  File "/home/william/.local/lib/python3.8/site-packages/requests_html.py", line 736, in close
    self.loop.run_until_complete(self._browser.close())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/browser.py", line 262, in close
    await self._closeCallback()  # Launcher.killChrome()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 218, in killChrome
    self._cleanup_tmp_user_data_dir()
  File "/home/william/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 133, in _cleanup_tmp_user_data_dir
    raise IOError('Unable to remove Temporary User Data')
OSError: Unable to remove Temporary User Data
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    runscrape()
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 140, in runscrape
    launchsite(i)
  File "/home/william/github/polo-web-scraper/scrapejs.py", line 125, in launchsite
    pool.starmap(scrape, links)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: Unable to remove Temporary User Data

